## Import Libraries

In [209]:
import pandas as pd
import numpy as np

## Load Data

In [ ]:
train_data = pd.read_csv('train_data.csv')
train_data.head()

,Created,CancelTime,DepartureTime,BillID,TicketID,ReserveStatus,UserID,Male,Price,CouponDiscount,...,Domestic,VehicleType,VehicleClass,TripReason,Vehicle,Cancel,HashPassportNumber_p,HashEmail,BuyerMobile,NationalCode
0,2022-10-23 09:38:49.110,NaN,2022-11-02 23:59:00,39710203,1091777.0,5,122885.0,True,6600000.0,34425.0,...,1,NaN,False,Work,Plane,0,NaN,66c7f29e3b92f3b77e20830ac29e7758037a53d2238a5b...,764974891906,477368495
1,2022-08-15 14:51:43.160,NaN,2022-08-18 04:15:00,38689463,1070902.0,5,876925.0,True,9500000.0,0.0,...,1,NaN,False,Int,Plane,0,NaN,b24634843858a4175d03422aa9e7211ec3b9f3ce4c481c...,27479149496,15987669
2,2022-09-20 17:25:27.250,NaN,2022-09-21 11:00:00,39245173,7624237.0,3,916640.0,False,2000000.0,0.0,...,1,VIP 2+1,True,Work,Bus,0,NaN,NaN,323657282999,667640412
3,2022-06-25 11:32:53.980,NaN,2022-06-26 08:30:00,37957585,2867547.0,2,NaN,False,40000.0,0.0,...,1,3 ستاره اتوبوسي,NaN,Int,Train,0,NaN,NaN,169459057632,392476186
4,2022-06-01 11:30:53.633,NaN,2022-06-02 23:00:00,37584530,7212559.0,3,NaN,True,1130000.0,0.0,...,1,اسکانیا تک صندلی ۳۱نفره,True,Int,Bus,0,NaN,NaN,408595008421,79497837

In [ ]:
test_data = pd.read_csv('test_data.csv')

## Preprocessing

In [ ]:
#1-delete some attributes
train_data.drop(['Created','CancelTime','BillID','TicketID','UserID','HashPassportNumber_p', 'HashEmail',
                  'BuyerMobile','NationalCode'], axis=1, inplace=True)
test_data.drop(['Created','CancelTime','BillID','TicketID','UserID','HashPassportNumber_p', 'HashEmail',
                  'BuyerMobile','NationalCode'], axis=1, inplace=True)

In [213]:
#2-checking null values
train_data.isna().sum()
test_data.isna().sum()

#3-fill null values
train_data['VehicleClass'].fillna(train_data['VehicleClass'].mode()[0], inplace=True)
test_data['VehicleClass'].fillna(train_data['VehicleClass'].mode()[0], inplace=True)
#other columns still remain

In [214]:
#4-add some attributes and encode

train_data['Male'] = train_data['Male'].astype(int)
test_data['Male'] = test_data['Male'].astype(int)

train_data['VehicleClass'] = train_data['VehicleClass'].astype(int)
test_data['VehicleClass'] = test_data['VehicleClass'].astype(int)


train2 = pd.get_dummies(train_data['Vehicle'])
train_data = pd.concat([train_data, train2], axis=1)
train_data.drop(['Vehicle'],axis=1,inplace=True)

test2 = pd.get_dummies(test_data['Vehicle'])
test_data = pd.concat([test_data, test2], axis=1)
test_data.drop(['Vehicle'],axis=1,inplace=True)


# train_data

In [215]:
train_data.drop(['From','To','Domestic'],axis=1,inplace=True)
test_data.drop(['From','To','Domestic'],axis=1,inplace=True)
#delete Domestic cause InternationalPlane is exactly vice versa. so one of them should be delete.
# train_data

In [216]:
train_data['FinalPrice'] = train_data['Price']-train_data['CouponDiscount']
test_data['FinalPrice'] = test_data['Price']-test_data['CouponDiscount']

train_data.drop(['Price','CouponDiscount'],axis=1,inplace=True)
test_data.drop(['Price','CouponDiscount'],axis=1,inplace=True)

train_data.head()

,DepartureTime,ReserveStatus,Male,VehicleType,VehicleClass,TripReason,Cancel,Bus,InternationalPlane,Plane,Train,FinalPrice
0,2022-11-02 23:59:00,5,1,NaN,0,Work,0,0,0,1,0,6565575.0
1,2022-08-18 04:15:00,5,1,NaN,0,Int,0,0,0,1,0,9500000.0
2,2022-09-21 11:00:00,3,0,VIP 2+1,1,Work,0,1,0,0,0,2000000.0
3,2022-06-26 08:30:00,2,0,3 ستاره اتوبوسي,1,Int,0,0,0,0,1,40000.0
4,2022-06-02 23:00:00,3,1,اسکانیا تک صندلی ۳۱نفره,1,Int,0,1,0,0,0,1130000.0

In [217]:
train_data

,DepartureTime,ReserveStatus,Male,VehicleType,VehicleClass,TripReason,Cancel,Bus,InternationalPlane,Plane,Train,FinalPrice
0,2022-11-02 23:59:00,5,1,NaN,0,Work,0,0,0,1,0,6565575.0
1,2022-08-18 04:15:00,5,1,NaN,0,Int,0,0,0,1,0,9500000.0
2,2022-09-21 11:00:00,3,0,VIP 2+1,1,Work,0,1,0,0,0,2000000.0
3,2022-06-26 08:30:00,2,0,3 ستاره اتوبوسي,1,Int,0,0,0,0,1,40000.0
4,2022-06-02 23:00:00,3,1,اسکانیا تک صندلی ۳۱نفره,1,Int,0,1,0,0,0,1130000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
101012,2022-06-04 12:10:00,5,1,بوئینگ 737,0,Int,0,0,0,1,0,5900000.0
101013,2022-11-01 15:30:00,2,1,4 ستاره اتوبوسي نگين,1,Work,0,0,0,0,1,926500.0
101014,2022-09-13 09:30:00,5,1,NaN,0,Int,0,0,1,0,0,30000000.0
101015,2022-09-29 17:30:00,3,1,25 نفره (VIP),1,Work,0,1,0,0,0,980000.0
101016,2022-04-05 17:10:00,2,1,4 ستاره 4 تخته ارگ,1,Work,0,0,0,0,1,3168000.0

In [218]:
from datetime import date

train_data['DepartureTime'] = pd.to_datetime(train_data['DepartureTime'])
train_data['Day'] = train_data['DepartureTime'].dt.day 
train_data['Month'] = train_data['DepartureTime'].dt.month 
train_data['S1'] = train_data['Month']*100
train_data['S2'] = train_data['S1']+train_data['Day']

conditions = [ (train_data['S2'] >= 301) & (train_data['S2'] <= 531),
               (train_data['S2'] > 531) & (train_data['S2'] < 901),
               (train_data['S2'] >= 901) & (train_data['S2'] <= 1130),
               (train_data['S2'] > 1130) , (train_data['S2'] <= 229) ]
values = ['Spring', 'Summer', 'Fall', 'Winter', 'Winter']

train_data['Season'] = np.select(conditions, values)
train_data.drop(['DepartureTime','Day','Month','S1','S2'],axis=1,inplace=True)



test_data['DepartureTime'] = pd.to_datetime(test_data['DepartureTime'])
test_data['Day'] = test_data['DepartureTime'].dt.day 
test_data['Month'] = test_data['DepartureTime'].dt.month 
test_data['S1'] = test_data['Month']*100
test_data['S2'] = test_data['S1']+test_data['Day']

conditions = [ (test_data['S2'] >= 301) & (test_data['S2'] <= 531),
               (test_data['S2'] > 531) & (test_data['S2'] < 901),
               (test_data['S2'] >= 901) & (test_data['S2'] <= 1130),
               (test_data['S2'] > 1130) , (test_data['S2'] <= 229) ]
values = ['Spring', 'Summer', 'Fall', 'Winter', 'Winter']

test_data['Season'] = np.select(conditions, values)
test_data.drop(['DepartureTime','Day','Month','S1','S2'],axis=1,inplace=True)

train_data.head()

,ReserveStatus,Male,VehicleType,VehicleClass,TripReason,Cancel,Bus,InternationalPlane,Plane,Train,FinalPrice,Season
0,5,1,NaN,0,Work,0,0,0,1,0,6565575.0,Fall
1,5,1,NaN,0,Int,0,0,0,1,0,9500000.0,Summer
2,3,0,VIP 2+1,1,Work,0,1,0,0,0,2000000.0,Fall
3,2,0,3 ستاره اتوبوسي,1,Int,0,0,0,0,1,40000.0,Summer
4,3,1,اسکانیا تک صندلی ۳۱نفره,1,Int,0,1,0,0,0,1130000.0,Summer

In [219]:
train_data['Season'].value_counts()

Fall      40216
Summer    34822
Spring    22483
Winter     3496
Name: Season, dtype: int64

In [ ]:
train3 = pd.get_dummies(train_data['Season'])
train_data = pd.concat([train_data, train3], axis=1)
train_data.drop(['Season'],axis=1,inplace=True)

test3 = pd.get_dummies(test_data['Season'])
test_data = pd.concat([test_data, test3], axis=1)
test_data.drop(['Season'],axis=1,inplace=True)

In [221]:
train_data.drop(['VehicleType'],axis=1,inplace=True)
test_data.drop(['VehicleType'],axis=1,inplace=True)

In [223]:
train_data

,ReserveStatus,Male,VehicleClass,TripReason,Cancel,Bus,InternationalPlane,Plane,Train,FinalPrice,Fall,Spring,Summer,Winter
0,5,1,0,Work,0,0,0,1,0,6565575.0,1,0,0,0
1,5,1,0,Int,0,0,0,1,0,9500000.0,0,0,1,0
2,3,0,1,Work,0,1,0,0,0,2000000.0,1,0,0,0
3,2,0,1,Int,0,0,0,0,1,40000.0,0,0,1,0
4,3,1,1,Int,0,1,0,0,0,1130000.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101012,5,1,0,Int,0,0,0,1,0,5900000.0,0,0,1,0
101013,2,1,1,Work,0,0,0,0,1,926500.0,1,0,0,0
101014,5,1,0,Int,0,0,1,0,0,30000000.0,1,0,0,0
101015,3,1,1,Work,0,1,0,0,0,980000.0,1,0,0,0
101016,2,1,1,Work,0,0,0,0,1,3168000.0,0,1,0,0

## Machine Learning Model

In [ ]:
# modeling 

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
model = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5), n_estimators=350)
df = train_data.drop(['TripReason'],axis=1)
model.fit(df, train_data['TripReason'])

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=5),
                   n_estimators=350)

## Evaluation

In [ ]:
# evaluate model
from sklearn.metrics import  f1_score

y_pred = model.predict(df)
f1_score(train_data['TripReason'], y_pred, average='binary', pos_label='Work')

0.8264811300864433

## Prediction

In [249]:
# predict test samples

class_pred = model.predict(test_data)
submission = pd.DataFrame(class_pred)
submission.columns = ['TripReason']
submission

      TripReason
0           Work
1           Work
2           Work
3           Work
4           Work
...          ...
43288       Work
43289       Work
43290       Work
43291       Work
43292       Work

[43293 rows x 1 columns]